/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT1_8 (coord A1), P1_8/J9[32]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT1_9 (coord B1), P1_9/J9[30]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT4_0 (coord P1), P4_0/J8[4]/SJ14[1]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIN0_RXD_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIN0_RXD_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIN0_RXD_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT4_1 (coord P2), P4_1/J8[3]/SJ15[1]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIN0_TXD_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIN0_TXD_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIN0_TXD_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT4_6 (coord N7), P4_6/J8[5]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LIN0_SLP_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LIN0_SLP_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LIN0_SLP_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIN0_SLP_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIN0_SLP_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIN0_SLP_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT4_5 (coord M8), P4_5/SJ11[3]/J8[6]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LIN0_M_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LIN0_M_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LIN0_M_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIN0_M_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIN0_M_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIN0_M_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT0_9 (coord A12), P0_9/J8[10]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LIN1_M_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LIN1_M_GPIO_PIN 9U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LIN1_M_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIN1_M_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIN1_M_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIN1_M_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT0_8 (coord C12), P0_8/J8[11]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LIN1_SLP_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LIN1_SLP_GPIO_PIN 8U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LIN1_SLP_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LIN1_SLP_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LIN1_SLP_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LIN1_SLP_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
