/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v16.0
processor: MCXN947
package_id: MCXN947VDF
mcu_data: ksdk2_0
processor_version: 16.3.0
board: FRDM-MCXN947
pin_labels:
- {pin_num: D1, pin_signal: PIO1_13/TRIG_IN3/FC4_P5/FC3_P1/CT2_MAT3/SCT0_OUT5/FLEXIO0_D21/EZH_PIO9/PLU_OUT3/ENET0_RXDV/CAN1_TXD/TSI0_CH22/ADC1_A13, label: 'P1_13/J9[27]',
  identifier: LIN1_TXD}
- {pin_num: P1, pin_signal: PIO4_0/WUU0_IN18/TRIG_IN6/FC2_P0/CT_INP16/EZH_PIO24/PLU_IN0/SINC0_MCLK3, label: 'P4_0/J8[4]/SJ14[1]', identifier: LIN0_RXD}
- {pin_num: D2, pin_signal: PIO1_12/WUU0_IN12/TRACE_CLK/FC4_P4/FC3_P0/CT2_MAT2/SCT0_OUT4/FLEXIO0_D20/EZH_PIO8/PLU_OUT2/ENET0_RXER/CAN1_RXD/TSI0_CH21/ADC1_A12, label: 'P1_12/J2[11]/J9[28]',
  identifier: LIN1_RXD}
- {pin_num: P2, pin_signal: PIO4_1/TRIG_IN7/FC2_P1/CT_INP17/EZH_PIO25/PLU_IN1, label: 'P4_1/J8[3]/SJ15[1]', identifier: LIN0_TXD}
- {pin_num: N7, pin_signal: PIO4_6/TRIG_OUT4/FC2_P6/CT_INP18/EZH_PIO30/PLU_CLK, label: 'P4_6/J8[5]', identifier: LIN0_SLP}
- {pin_num: M8, pin_signal: PIO4_5/FC2_P5/CT_INP15/EZH_PIO29/PLU_IN5/SINC0_MBIT4, label: 'P4_5/SJ11[3]/J8[6]', identifier: LIN0_M}
- {pin_num: A12, pin_signal: PIO0_9/FC0_P5/CT_INP1/FLEXIO0_D1/ADC0_B9, label: 'P0_9/J8[10]', identifier: LIN1_M}
- {pin_num: C12, pin_signal: PIO0_8/FC0_P4/CT_INP0/FLEXIO0_D0/ADC0_B8, label: 'P0_8/J8[11]', identifier: LIN1_SLP}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A1, peripheral: LP_FLEXCOMM4, signal: LPFLEXCOMM_P0, pin_signal: PIO1_8/WUU0_IN10/LPTMR1_ALT3/TRACE_DATA0/FC4_P0/FC5_P4/CT_INP8/SCT0_OUT2/FLEXIO0_D16/EZH_PIO4/PLU_OUT0/ENET0_TXD2/I3C1_SDA/TSI0_CH17/ADC1_A8,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, passive_filter: disable, pull_value: low, input_buffer: enable,
    invert_input: normal}
  - {pin_num: B1, peripheral: LP_FLEXCOMM4, signal: LPFLEXCOMM_P1, pin_signal: PIO1_9/TRACE_DATA1/FC4_P1/FC5_P5/CT_INP9/SCT0_OUT3/FLEXIO0_D17/EZH_PIO5/PLU_OUT1/ENET0_TXD3/I3C1_SCL/TSI0_CH18/ADC1_A9,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: P1, peripheral: LP_FLEXCOMM2, signal: LPFLEXCOMM_P0, pin_signal: PIO4_0/WUU0_IN18/TRIG_IN6/FC2_P0/CT_INP16/EZH_PIO24/PLU_IN0/SINC0_MCLK3}
  - {pin_num: P2, peripheral: LP_FLEXCOMM2, signal: LPFLEXCOMM_P1, pin_signal: PIO4_1/TRIG_IN7/FC2_P1/CT_INP17/EZH_PIO25/PLU_IN1}
  - {pin_num: N7, peripheral: GPIO4, signal: 'GPIO, 6', pin_signal: PIO4_6/TRIG_OUT4/FC2_P6/CT_INP18/EZH_PIO30/PLU_CLK, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: M8, peripheral: GPIO4, signal: 'GPIO, 5', pin_signal: PIO4_5/FC2_P5/CT_INP15/EZH_PIO29/PLU_IN5/SINC0_MBIT4, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: A12, peripheral: GPIO0, signal: 'GPIO, 9', pin_signal: PIO0_9/FC0_P5/CT_INP1/FLEXIO0_D1/ADC0_B9, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: C12, peripheral: GPIO0, signal: 'GPIO, 8', pin_signal: PIO0_8/FC0_P4/CT_INP0/FLEXIO0_D0/ADC0_B8, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: D11, peripheral: LP_FLEXCOMM0, signal: LPFLEXCOMM_P0, pin_signal: PIO0_12/FC1_P4/FC0_P0/CT0_MAT2/FLEXIO0_D4/ADC0_B12}
  - {pin_num: F12, peripheral: LP_FLEXCOMM0, signal: LPFLEXCOMM_P1, pin_signal: PIO0_13/FC1_P5/FC0_P1/CT0_MAT3/FLEXIO0_D5/ADC0_B13}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Enables the clock for GPIO0: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio0);
    /* Enables the clock for GPIO4: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio4);
    /* Enables the clock for PORT0 controller: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port0);
    /* Enables the clock for PORT1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port1);
    /* Enables the clock for PORT4: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port4);

    gpio_pin_config_t LIN1_SLP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO0_8 (pin C12)  */
    GPIO_PinInit(BOARD_INITPINS_LIN1_SLP_GPIO, BOARD_INITPINS_LIN1_SLP_PIN, &LIN1_SLP_config);

    gpio_pin_config_t LIN1_M_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO0_9 (pin A12)  */
    GPIO_PinInit(BOARD_INITPINS_LIN1_M_GPIO, BOARD_INITPINS_LIN1_M_PIN, &LIN1_M_config);

    gpio_pin_config_t LIN0_M_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO4_5 (pin M8)  */
    GPIO_PinInit(BOARD_INITPINS_LIN0_M_GPIO, BOARD_INITPINS_LIN0_M_PIN, &LIN0_M_config);

    gpio_pin_config_t LIN0_SLP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO4_6 (pin N7)  */
    GPIO_PinInit(BOARD_INITPINS_LIN0_SLP_GPIO, BOARD_INITPINS_LIN0_SLP_PIN, &LIN0_SLP_config);

    /* PORT0_12 (pin D11) is configured as FC0_P0 */
    PORT_SetPinMux(PORT0, 12U, kPORT_MuxAlt3);

    PORT0->PCR[12] = ((PORT0->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_13 (pin F12) is configured as FC0_P1 */
    PORT_SetPinMux(PORT0, 13U, kPORT_MuxAlt3);

    PORT0->PCR[13] = ((PORT0->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_8 (pin C12) is configured as PIO0_8 */
    PORT_SetPinMux(BOARD_INITPINS_LIN1_SLP_PORT, BOARD_INITPINS_LIN1_SLP_PIN, kPORT_MuxAlt0);

    PORT0->PCR[8] = ((PORT0->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_9 (pin A12) is configured as PIO0_9 */
    PORT_SetPinMux(BOARD_INITPINS_LIN1_M_PORT, BOARD_INITPINS_LIN1_M_PIN, kPORT_MuxAlt0);

    PORT0->PCR[9] = ((PORT0->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    const port_pin_config_t DEBUG_UART_RX = {/* Internal pull-up/down resistor is disabled */
                                             .pullSelect = kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             .pullValueSelect = kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             .slewRate = kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             .openDrainEnable = kPORT_OpenDrainDisable,
                                             /* Low drive strength is configured */
                                             .driveStrength = kPORT_LowDriveStrength,
                                             /* Pin is configured as FC4_P0 */
                                             .mux = kPORT_MuxAlt2,
                                             /* Digital input enabled */
                                             .inputBuffer = kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             .invertInput = kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             .lockRegister = kPORT_UnlockRegister};
    /* PORT1_8 (pin A1) is configured as FC4_P0 */
    PORT_SetPinConfig(BOARD_INITPINS_DEBUG_UART_RX_PORT, BOARD_INITPINS_DEBUG_UART_RX_PIN, &DEBUG_UART_RX);

    const port_pin_config_t DEBUG_UART_TX = {/* Internal pull-up/down resistor is disabled */
                                             .pullSelect = kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             .pullValueSelect = kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             .slewRate = kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             .openDrainEnable = kPORT_OpenDrainDisable,
                                             /* Low drive strength is configured */
                                             .driveStrength = kPORT_LowDriveStrength,
                                             /* Pin is configured as FC4_P1 */
                                             .mux = kPORT_MuxAlt2,
                                             /* Digital input enabled */
                                             .inputBuffer = kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             .invertInput = kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             .lockRegister = kPORT_UnlockRegister};
    /* PORT1_9 (pin B1) is configured as FC4_P1 */
    PORT_SetPinConfig(BOARD_INITPINS_DEBUG_UART_TX_PORT, BOARD_INITPINS_DEBUG_UART_TX_PIN, &DEBUG_UART_TX);

    /* PORT4_0 (pin P1) is configured as FC2_P0 */
    PORT_SetPinMux(BOARD_INITPINS_LIN0_RXD_PORT, BOARD_INITPINS_LIN0_RXD_PIN, kPORT_MuxAlt2);

    PORT4->PCR[0] = ((PORT4->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_1 (pin P2) is configured as FC2_P1 */
    PORT_SetPinMux(BOARD_INITPINS_LIN0_TXD_PORT, BOARD_INITPINS_LIN0_TXD_PIN, kPORT_MuxAlt2);

    PORT4->PCR[1] = ((PORT4->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_5 (pin M8) is configured as PIO4_5 */
    PORT_SetPinMux(BOARD_INITPINS_LIN0_M_PORT, BOARD_INITPINS_LIN0_M_PIN, kPORT_MuxAlt0);

    PORT4->PCR[5] = ((PORT4->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_6 (pin N7) is configured as PIO4_6 */
    PORT_SetPinMux(BOARD_INITPINS_LIN0_SLP_PORT, BOARD_INITPINS_LIN0_SLP_PIN, kPORT_MuxAlt0);

    PORT4->PCR[6] = ((PORT4->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
